### PR TITLE
oonf-olsrd2: fix olsrd2

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Further, delete PKG_REV.

### CODE REVIEW

**Comment by neheb** [comment]
Needs the other PR as well.

Also, https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/routing/

**Comment by PolynomialDivision** [comment]
> Needs the other PR as well.
> 
> Also, https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/routing/

Yep. However, the source code is not existing. I'm a bit confused what I'm doing wrong.

**Comment by neheb** [comment]
Closed my other one.

**Comment by PolynomialDivision** [comment]
I'm also fixing the other both with your commits.

**Pull request merged**
