### PR TITLE
[22.03] opennds: Release v10.1.1

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net

Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64

Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 23.05, 22.03

Description:
opennds (10.1.1)
  * This version contains some minor bug fixes and documentation updates
  * Fix - send only contents of buffer, not entire buffer when serving page511 [bluewavenet]
  * Fix - Set fas_remotefqdn to gw_fqdn when overriding FAS settings [bluewavenet]
  * Fix - use absolute path for css and images in ThemeSpec [bluewavenet]
  * Fix - revert to old option names without underscores [bluewavenet]
  * Fix - FAS URL when fas_remotefqdn is not set [bluewavenet]

Signed-off-by: Rob White <rob@blue-wave.net>
(cherry picked from commit 26f5f0f812c73a3d26f9643fbd3da7f56f5e9a8a)

### CODE REVIEW

**Comment by bluewavenet** [comment]
@BKPepe @PolynomialDivision @mwarning 
CI still broken here though.....

**Comment by BKPepe** [comment]
It's because @PolynomialDivision did not backport such CI/CD changes to 22.03 branch. I will do that today.

**Comment by bluewavenet** [comment]
@BKPepe 
On the one hand, 22.03 is, at this moment, the current stable release so merging is desirable.
On the other hand, 22.03 is rapidly approaching EOL. The work required to fix CI given architecture naming changes is more than just a cherry pick, so is it worth the effort given that is becoming, as time progresses, more unlikely that any other packages will be updated?

We could:
1. Fix CI and merge openNDS v10.1.1 (preferred option)
2. Leave CI broken and merge v10.1.1 (as was done for v10.1.0 and is the second preferred option)
3. Don't do anything (least desirable)

openNDS v10.1.1 fixes some relatively minor bugs effecting some common modes of operation for which there are workarounds. So a merge is desirable but not essential.

**Comment by BKPepe** [comment]
Its not CVE not any other major issues such security vulnerabilities, etc.
So no need to hurry at all.

Dne čt 20. 7. 2023 9:47 uživatel Rob White ***@***.***>
napsal:

**Comment by bluewavenet** [comment]
@BKPepe 
As fixing CI is additional workload for you and merging this PR is desirable but not essential, then I will leave it in your capable hands ;-)

**Comment by bluewavenet** [comment]
Closed as superseded by release v10.1.2

**Pull request closed without merging**
