### PR TITLE
[23.05] nodogsplash: update to 5.0.1

### PR DESCRIPTION
**Pull request by mwarning**
Cherry picked from https://github.com/openwrt/routing/pull/997 since this includes an important security fix to protect against path tracersal attacks.

### CODE REVIEW

**Comment by mwarning** [comment]
@bluewavenet @lynxis fyi

**Comment by mwarning** [comment]
@PolynomialDivision hi, can you have a second look here? Thank you.

**Comment by BKPepe** [comment]
Hmm, too bad that in the commit message, there are not explained changes like why they are additional dependencies, why the conflict was changed, etc. Because it looks like usual bump, which it isnt. :-(

**Comment by mwarning** [comment]
Ah, I see. Yes, too bad.  For the record, the dependencies were missing.

**Comment by mwarning** [comment]
@BKPepe there is probably no point in adding it to the commit now in this MR. If that's ok, then let's merge it.

**Pull request merged**
