### PR TITLE
opennds: Release v9.4.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0, 19.07.8

Description:
This version adds new functionality, and fixes some issues
  * Add - Error message in fas-aes-https if shared key is mismatched [bluewave.net]
  * Fix - and refactor error 511 page generation[bluewave.net]
  * Fix - and refactor dnsmasq configuration [bluewave.net]
  * Fix - Typographic error preventing RFC8910 disable [bluewave.net]
  * Add - gateway address and gatewayfqdn to ndsctl json output [bluewave.net]
  * Add - RFC8910 housekeeping on startup and shutdown [bluewave.net]
  * Add - correctly apply dhcp option 114 for generic Linux [bluewave.net]
  * Add - reading of configured ndsctlsocket in ndsctl utility[bluewave.net]
  * Add - use send_error 200 for MHD watchdog [bluewave.net]
  * Add - generation of page_511 html by library script [bluewave.net]
  * Add - extend debuglevel support to library scripts [bluewave.net]
  * Refactor - fas-aes-https to simplify and make customisation of http easier [bluewave.net]
  * Add - library script for error 511 page, allowing customisation [bluewave.net]
  * Add - make authmon report connection error details [bluewave.net]
  * Fix- remove unwanted debug message in ndsctl [bluewave.net]
  * Add - RFC8910 support by default [bluewave.net]
  * Add - display status page when accessing /login when authenticated [bluewave.net]
  * Add - MHD response to RFC8910 requests [bluewave.net]
  * Add - Dnsmasq RFC8910 configuration [bluewave.net]
  * Add - send error 511 in response to unsupported http method [bluewave.net]
  * Add - Check for ca-bundle on OpenWrt, if not installed, add syslog messages and terminate [bluewave.net]
  * Add - Make ndsctl use the configured value for socket path if set and deprecate -s option [bluewave.net]
  * Add - Warning message when Walled Garden port 80 is allowed [bluewave.net]
  * Fix - remove un-needed pthread_kill in termination_handler() [bluewave.net] [T-X]
  * Fix - debug messages from authmon.sh [bluewave.net]
  * Fix - Allow disabling gateway fqdn, facilitating access to router port 80 [bluewave.net]
  * Fix - Segfault in ndsctl when -s option is used incorrectly [bluewave.net] [T-X]
  * Fix - Typo making calculation of ul/dl rates incorrect [bluewave.net]
  * Fix - Allow port 80 to be configured in the Walled Garden [bluewave.net]

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@PolynomialDivision @mwarning 
It seems Test x86_64 is broken with error:
`WARNING: can't open config file: /builder/shared-workdir/build/staging_dir/host/etc/ssl/openssl.cnf`

**Comment by bluewavenet** [comment]
@PolynomialDivision @mwarning 
Making it run again with another commit a few hours later and it gives a different error, so maybe the test build will sort itself out...
Or does it need looking at?

**Comment by PolynomialDivision** [comment]
I think x86 buildchain is currently broken. No idea what happend. But openwrt/packages has also similar issues.

**Comment by PolynomialDivision** [comment]
Should I merge?

**Comment by bluewavenet** [comment]
@PolynomialDivision 
Ooops. Lets try that again...

**Comment by PolynomialDivision** [comment]
Please squash the latest commits into 1?

**Comment by bluewavenet** [comment]
@PolynomialDivision 

> Please squash the latest commits into 1?

Now I find myself looking into the mouth of the OCD Vortex of Doom ;-)

**Comment by PolynomialDivision** [comment]
`git rebase -i HEAD~3` then write squash the last commits. Change your commit message to include everything. Done. ;)

**Comment by bluewavenet** [comment]
@PolynomialDivision 

> Should I merge?

Yes please

**Comment by PolynomialDivision** [comment]
LGTM. Will wait for CI tests and merge afterwards.

**Comment by bluewavenet** [comment]
@PolynomialDivision 
Thanks!

**Pull request merged**
