### PR TITLE
batman-adv: update packages to version 2021.2

### PR DESCRIPTION
**Pull request by ecsv**
Maintainer: @simonwunderlich 
Compile tested: x86
Run tested: x86, qemu-system-x86_64

Description:

batman-adv
==========

* support latest kernels (4.4 - 5.14)
* coding style cleanups and refactoring
* add MRD + routable IPv4 multicast with bridges support
* rewrite of broadcast queuing
* bugs squashed:
  * avoid kernel warnings on timing related checks

batctl
====

* manpage cleanups
* coding style cleanups and refactoring

alfred
======

* manpage cleanups

### CODE REVIEW

**Comment by neheb** [comment]
Fails:

```
home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:67:15: error: implicit declaration of function 'br_multicast_list_adjacent'; did you mean 'br_multicast_has_router_adjacent'? [-Werror=implicit-function-declaration]
   67 |         ret = br_multicast_list_adjacent(dev, &bridge_mcast_list);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |               br_multicast_has_router_adjacent
In file included from ./include/uapi/linux/stddef.h:2,
                 from ./include/linux/stddef.h:5,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/stddef.h:3,
                 from ./include/uapi/linux/posix_types.h:5,
                 from ./include/uapi/linux/types.h:14,
                 from ./include/linux/types.h:6,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/types.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:6,
                 from <command-line>:
./include/linux/kernel.h:853:58: error: invalid use of undefined type 'struct br_ip_list'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                                                          ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:27: note: in expansion of macro '__same_type'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:522:9: note: in expansion of macro 'list_entry'
  522 |         list_entry((ptr)->next, type, member)
      |         ^~~~~~~~~~
./include/linux/list.h:715:20: note: in expansion of macro 'list_first_entry'
  715 |         for (pos = list_first_entry(head, typeof(*pos), member),        \
      |                    ^~~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/compiler_types.h:135:41: error: invalid use of undefined type 'struct br_ip_list'
  135 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^~~~~~~~~~~~~~~~~~
./include/linux/stddef.h:17:33: note: in expansion of macro '__compiler_offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:856:28: note: in expansion of macro 'offsetof'
  856 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:522:9: note: in expansion of macro 'list_entry'
  522 |         list_entry((ptr)->next, type, member)
      |         ^~~~~~~~~~
./include/linux/list.h:715:20: note: in expansion of macro 'list_first_entry'
  715 |         for (pos = list_first_entry(head, typeof(*pos), member),        \
      |                    ^~~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/kernel.h:3,
                 from ./include/linux/uio.h:8,
                 from ./include/linux/socket.h:8,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/socket.h:3,
                 from ./include/uapi/linux/in.h:24,
                 from ./include/linux/in.h:19,
                 from ./include/net/addrconf.h:24,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/net/addrconf.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:54,
                 from <command-line>:
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/kernel.h:852:33: note: in definition of macro 'container_of'
  852 |         void *__mptr = (void *)(ptr);                                   \
      |                                 ^~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:716:21: note: in expansion of macro 'list_next_entry'
  716 |                 n = list_next_entry(pos, member);                       \
      |                     ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/uapi/linux/stddef.h:2,
                 from ./include/linux/stddef.h:5,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/stddef.h:3,
                 from ./include/uapi/linux/posix_types.h:5,
                 from ./include/uapi/linux/types.h:14,
                 from ./include/linux/types.h:6,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/types.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:6,
                 from <command-line>:
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:27: note: in expansion of macro '__same_type'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:716:21: note: in expansion of macro 'list_next_entry'
  716 |                 n = list_next_entry(pos, member);                       \
      |                     ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:58: error: invalid use of undefined type 'struct br_ip_list'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                                                          ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:27: note: in expansion of macro '__same_type'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:716:21: note: in expansion of macro 'list_next_entry'
  716 |                 n = list_next_entry(pos, member);                       \
      |                     ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:854:27: note: in expansion of macro '__same_type'
  854 |                          !__same_type(*(ptr), void),                    \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:716:21: note: in expansion of macro 'list_next_entry'
  716 |                 n = list_next_entry(pos, member);                       \
      |                     ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/compiler_types.h:135:41: error: invalid use of undefined type 'struct br_ip_list'
  135 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^~~~~~~~~~~~~~~~~~
./include/linux/stddef.h:17:33: note: in expansion of macro '__compiler_offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:856:28: note: in expansion of macro 'offsetof'
  856 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:716:21: note: in expansion of macro 'list_next_entry'
  716 |                 n = list_next_entry(pos, member);                       \
      |                     ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/list.h:3,
                 from ./include/linux/smp.h:12,
                 from ./arch/arm64/include/asm/arch_timer.h:18,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:65,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:73,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/time.h:3,
                 from ./include/linux/skbuff.h:15,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/skbuff.h:3,
                 from ./include/linux/tcp.h:17,
                 from ./include/linux/ipv6.h:87,
                 from ./include/net/addrconf.h:50,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/net/addrconf.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:54,
                 from <command-line>:
./include/linux/list.h:715:64: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  715 |         for (pos = list_first_entry(head, typeof(*pos), member),        \
      |                                                                ^
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/list.h:619:14: error: invalid use of undefined type 'struct br_ip_list'
  619 |         (&pos->member == (head))
      |              ^~
./include/linux/list.h:717:15: note: in expansion of macro 'list_entry_is_head'
  717 |              !list_entry_is_head(pos, head, member);                    \
      |               ^~~~~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/kernel.h:3,
                 from ./include/linux/uio.h:8,
                 from ./include/linux/socket.h:8,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/socket.h:3,
                 from ./include/uapi/linux/in.h:24,
                 from ./include/linux/in.h:19,
                 from ./include/net/addrconf.h:24,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/net/addrconf.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:54,
                 from <command-line>:
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/kernel.h:852:33: note: in definition of macro 'container_of'
  852 |         void *__mptr = (void *)(ptr);                                   \
      |                                 ^~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:718:27: note: in expansion of macro 'list_next_entry'
  718 |              pos = n, n = list_next_entry(n, member))
      |                           ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/uapi/linux/stddef.h:2,
                 from ./include/linux/stddef.h:5,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/stddef.h:3,
                 from ./include/uapi/linux/posix_types.h:5,
                 from ./include/uapi/linux/types.h:14,
                 from ./include/linux/types.h:6,
                 from /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/linux/types.h:4,
                 from /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:6,
                 from <command-line>:
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:27: note: in expansion of macro '__same_type'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:718:27: note: in expansion of macro 'list_next_entry'
  718 |              pos = n, n = list_next_entry(n, member))
      |                           ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:58: error: invalid use of undefined type 'struct br_ip_list'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                                                          ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:27: note: in expansion of macro '__same_type'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:718:27: note: in expansion of macro 'list_next_entry'
  718 |              pos = n, n = list_next_entry(n, member))
      |                           ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/list.h:555:25: error: invalid use of undefined type 'struct br_ip_list'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
./include/linux/compiler_types.h:295:23: note: in definition of macro '__compiletime_assert'
  295 |                 if (!(condition))                                       \
      |                       ^~~~~~~~~
./include/linux/compiler_types.h:315:9: note: in expansion of macro '_compiletime_assert'
  315 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:853:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  853 |         BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) &&   \
      |         ^~~~~~~~~~~~~~~~
./include/linux/kernel.h:854:27: note: in expansion of macro '__same_type'
  854 |                          !__same_type(*(ptr), void),                    \
      |                           ^~~~~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:718:27: note: in expansion of macro 'list_next_entry'
  718 |              pos = n, n = list_next_entry(n, member))
      |                           ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/compiler_types.h:135:41: error: invalid use of undefined type 'struct br_ip_list'
  135 | #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
      |                                         ^~~~~~~~~~~~~~~~~~
./include/linux/stddef.h:17:33: note: in expansion of macro '__compiler_offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~~
./include/linux/kernel.h:856:28: note: in expansion of macro 'offsetof'
  856 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
./include/linux/list.h:511:9: note: in expansion of macro 'container_of'
  511 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
./include/linux/list.h:555:9: note: in expansion of macro 'list_entry'
  555 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
./include/linux/list.h:718:27: note: in expansion of macro 'list_next_entry'
  718 |              pos = n, n = list_next_entry(n, member))
      |                           ^~~~~~~~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:73:9: note: in expansion of macro 'list_for_each_entry_safe'
   73 |         list_for_each_entry_safe(br_ip_entry, tmp, &bridge_mcast_list, list) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from <command-line>:
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:74:32: error: invalid use of undefined type 'struct br_ip_list'
   74 |                 if (br_ip_entry->addr.proto == htons(ETH_P_IPV6) &&
      |                                ^~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:75:61: error: invalid use of undefined type 'struct br_ip_list'
   75 |                     ipv6_addr_is_ll_all_routers(&br_ip_entry->addr.dst.ip6))
      |                                                             ^~
/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/compat-hacks.h:78:38: error: invalid use of undefined type 'struct br_ip_list'
   78 |                 list_del(&br_ip_entry->list);
      |                                      ^~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:280: /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/net/batman-adv/bat_algo.o] Error 1
make[3]: *** [Makefile:1822: /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/net/batman-adv] Error 2
make[3]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.60'
make[2]: *** [Makefile:92: /home/mangix/devstuff/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/batman-adv-2021.2/.built] Error 2
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/routing/batman-adv'
time: package/feeds/routing/batman-adv/compile#0.67#0.19#0.85
    ERROR: package/feeds/routing/batman-adv failed to build.
make[1]: *** [package/Makefile:116: package/feeds/routing/batman-adv/compile] Error 1
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:230: package/batman-adv/compile] Error 2
```

**Comment by ecsv** [comment]
@neheb What config? Because it did build for me and for the automatic build checks

**Comment by neheb** [comment]
5.10 kernel. probably need testing features enabled.

**Comment by ecsv** [comment]
I can reproduce it on commit 9baca410644b ("ipq806x: fix min<>target opp-microvolt DTS mixup") with config 

````
./scripts/diffconfig.sh 
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_generic=y
CONFIG_TARGET_x86_generic_DEVICE_generic=y
CONFIG_BATMAN_ADV_BATMAN_V=y
CONFIG_BATMAN_ADV_BLA=y
CONFIG_BATMAN_ADV_DAT=y
CONFIG_BATMAN_ADV_MCAST=y
CONFIG_BATMAN_ADV_SYSFS=y
CONFIG_LINUX_5_10=y
CONFIG_PACKAGE_batctl-default=y
CONFIG_PACKAGE_iw=y
CONFIG_PACKAGE_iwinfo=y
CONFIG_PACKAGE_kmod-batman-adv=y
CONFIG_PACKAGE_kmod-cfg80211=y
CONFIG_PACKAGE_kmod-crypto-crc32c=y
CONFIG_PACKAGE_kmod-crypto-hash=y
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-lib-crc32c=y
CONFIG_PACKAGE_kmod-mdio-devres=y
CONFIG_PACKAGE_libiwinfo=y
CONFIG_PACKAGE_libiwinfo-data=y
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_TESTING_KERNEL=y
# CONFIG_BATMAN_ADV_DEBUGFS is not set
CONFIG_BATMAN_ADV_SYSFS=y
````

I will create a PR for the 5.10 support i a sec

**Pull request merged**
