### PR TITLE
opennds: Release v9.2.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0-rc3, 19.07.7

Description:
This version adds new functionality, improves performance, adds documentation and fixes an issue
  * Add - new config options to ndsctl status [bluewave.net]
  * Add - Readthedocs / man documentation for configuration options [bluewave.net]
  * Add - Faster convergence of average rates to configured rate quotas [bluewave.net]
  * Add - BinAuth parse authenticated client database for client data [bluewave.net]
  * Add - Use heap allocation for http page buffer allowing large page sizes [bluewave.net]
  * Fix - fail to serve downloaded images on custom themespec [bluewave.net]

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Why is the Makfile deleting the opendns firewall section?
https://github.com/openwrt/routing/blob/b99aba0eef6f75e0a74655a333b440925b420052/opennds/Makefile#L79

**Comment by bluewavenet** [comment]
@PolynomialDivision 
This is in the `define Package/opennds/postrm` section and is code for `opkg remove` to run to clean up after an uninstall.

**Comment by bluewavenet** [comment]
@mwarning

**Comment by PolynomialDivision** [comment]
> @mwarning

I can also merge... ^^ But I can wait for @mwarning

**Comment by bluewavenet** [comment]
@PolynomialDivision 
Thankyou!

**Comment by PolynomialDivision** [comment]
Could you also try compiling with gcc11?

**Pull request merged**
