### PR TITLE
minimalist-pcproxy,pimgc,mcproxy,mrd6: include PKG_MIRROR_HASH

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainers: @sbyx @fingon @Oryon 
Compile tested: mediatek, openwrt master
Run tested: N/A

Description:
I've ran `make package/{minimalist-pcproxy,pimgc,mcprox,mrd6}/{download,check} FIXUP=1` to add the `PKG_MIRROR_HASH` variable to these packages that were missing it.

Setting the variable avoids recreating the tarball every time the package is rebuilt.  It also avoids rebuilds if you run `make` back-to-back without changing anything.

### CODE REVIEW

**Comment by cotequeiroz** [comment]
It looks like the Ci did not agree with my mcproxy hash.  I will investigate it.  Meanwhile, let's see if the rest of the pack works.

**Comment by PolynomialDivision** [comment]
Hey @sbyx @fingon @Oryon
Can you ack?

**Comment by PolynomialDivision** [comment]
I looked at the history of the Makefiles and I think they are now maintained by the "whole routing feed". I will merge.

**Comment by BKPepe** [comment]
Can this be backported to OpenWrt 21.02, please? Should I create a pull request?

**Pull request merged**
