### PR TITLE
babeld: add add_filter function

### PR DESCRIPTION
**Pull request by PolynomialDivision**
I just tried to add simple filter. However, this does not work. Any idea what is missing to add a filter @jech?

E.g.

     in if eth0 metric 128

should be

    ubus call babeld add_filter '{"ifname":"eth0", "type":"input", "metric":128}'

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Maybe I was to tired yesterday. I just tested everything again and it works flawlessly. Are you fine with adding this already @jech? I will go on defining all possible filter functions, however, I urgently need this functionality only for ipv6 and all routes on an interface.

**Comment by jech** [comment]
I'll change the interface a little bit, to make it less error-prone, but the principle will remain the same.  Please give me a couple of days.

**Comment by PolynomialDivision** [comment]
> I'll change the interface a little bit, to make it less error-prone, but the principle will remain the same. Please give me a couple of days.

Works perfectly! Thanks a lot. I would merge?

**Comment by jech** [comment]
Merged.

**Comment by PolynomialDivision** [comment]
Great than I will also merge this PR. :) Maybe time for a new release?

**Comment by jech** [comment]
I was planning to merge v4-via-v6 first, but it might indeed be worthwile to release before then.

**Pull request merged**
