### PR TITLE
bird2: bump to version 2.0.10

### PR DESCRIPTION
**Pull request by mbargo23**
Signed-off-by: Jan Betik <jan.betik@nic.cz>

Maintainer: @tohojo 

Description: bump to 2.0.10

### CODE REVIEW

**Comment by tohojo** [comment]
Ah, thanks for the update!

Care to take a look if the patch in `patches/000-ospf-bus-error.patch` might be worth applying upstream?

**Comment by PolynomialDivision** [comment]
Please also backport to 21.02 and 22.03.

**Comment by mbargo23** [comment]
I have asked the developers about the patch and they have stated to keep it.

**Comment by tohojo** [comment]
"M. Bargo" ***@***.***> writes:

> I have asked the developers about the patch and they have stated to
> keep it.

Alright, thanks for checking!

**Pull request merged**
