### PR TITLE
[WIP] sroamd: add sroamd

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@jech
What do you think? Should we read everything from `/etc/config/network` and just give the interface, or should we make everything configurable?

**Comment by jech** [comment]
I suggest making as few things configurable as reasonable; if more configuration is needed, it can easily be added at a later date.

**Comment by BKPepe** [comment]
What's happening with this? This seems stalled, so I prefer if you can close it and once you have time to continue on this, then reopen it.

**Comment by jech** [comment]
I'm the upstream author of sroamd.  Sroamd is not ready for general usage, the flooding protocol is not reliable enough yet.  Sroamd is currently on hold, since I'm busy with other things, but I plan to come back to it at some point.

Please drop me a note by personal mail <jch@irif.fr> if you're interested in working on sroamd.

**Pull request closed without merging**
