### PR TITLE
opennds: [21.02] Backport of Release v9.2.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0-rc3, 19.07.7

Description:
This version adds new functionality, improves performance, adds documentation and fixes an issue
  * Add - new config options to ndsctl status [bluewave.net]
  * Add - Readthedocs / man documentation for configuration options [bluewave.net]
  * Add - Faster convergence of average rates to configured rate quotas [bluewave.net]
  * Add - BinAuth parse authenticated client database for client data [bluewave.net]
  * Add - Use heap allocation for http page buffer allowing large page sizes [bluewave.net]
  * Fix - fail to serve downloaded images on custom themespec [bluewave.net]

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@PolynomialDivision @mwarning

**Comment by PolynomialDivision** [comment]
lgtm, but will wait first for CI for testing. ;)

**Comment by PolynomialDivision** [comment]
Actually, if you do a backport you just cherry-pick -x and let away all the [21.02] stuff in the commit header (except for github title).

**Comment by bluewavenet** [comment]
@PolynomialDivision 

>  but will wait first for CI for testing

Of course ;-)

> just cherry-pick -x

I am not familiar with this at all, but when time permits will investigate to potentially use it next time.

**Pull request merged**
