### PR TITLE
batman-adv: compat: Add atomic mc_fowarding support for stable kernels

### PR DESCRIPTION
**Pull request by zhanhb**
Compile tested: ath79/nand
Also see: #850

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @ecsv

**Comment by ecsv** [comment]
@PolynomialDivision why do you ping me?

And the long line is not too nice to read and incomplete. See the upstream version: 

* https://git.open-mesh.org/batman-adv.git/commit/f07a0c37ab278fb6a9e95cad89429b1282f1ab59
* https://git.open-mesh.org/batman-adv.git/commit/350adcaec82fbaa358a2406343b6130ac8dad126

Please cherry pick that instead and add the "Origin: " tags like in all other patches

**Comment by ecsv** [comment]
@zhanhb can you please add a commit message with more information. Something like you can see in https://github.com/ecsv/routing/commits/batadv-2022.0

**Comment by zhanhb** [comment]
I'm sorry, I'm not good at English.

**Comment by ecsv** [comment]
Thanks. Now we just have to tell the maintainer to merge the changes. @simonwunderlich, can you please merge this branch?

I will take care of backporting it to OpenWrt 21.02 and OpenWrt 22.03

**Comment by zhanhb** [comment]
Closed for #852 is preferred.

**Comment by PolynomialDivision** [comment]
@ecsv I thought you are the maintainer. Sorry.

**Pull request closed without merging**
