### PR TITLE
ci: add commit linting

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by BKPepe** [comment]
This should be first added to packages repository and reviewed there.

**Comment by PolynomialDivision** [comment]
> This should be first added to packages repository and reviewed there.

It had some serious limitations and I don't find it useful anymore. Closing.

**Comment by BKPepe** [comment]
For the sake of completeness, would you mind sharing which serious limitations it have?

**Comment by PolynomialDivision** [comment]
> For the sake of completeness, would you mind sharing which serious limitations it have?

I am sorry, but I can not remember correctly. Do you think such linting would be useful in general? Maybe I can go into this again and check if I can tweak all configurations that it is useful for us/me.

**Pull request closed without merging**
