### PR TITLE
bird2: add test.sh for bird

### PR DESCRIPTION
**Pull request by bradfordzhang**
Maintainer: @tohojo 
Compile tested: x86_64 generic
Run tested: x86_64 generic test done

Description: add test.sh for bird2

### CODE REVIEW

**Comment by BKPepe** [comment]
CI fails:
```
Testing package bird2 in version  from bird2
No pre-test.sh script available
Installing bird2 (2.15.1-r1) to root...
Failed to connect to ubus
Configuring bird2.
Use package specific test.sh
BIRD version 2.15.1
Test failed
```

**Comment by bradfordzhang** [comment]
> CI fails:
> ```
> Testing package bird2 in version  from bird2
> No pre-test.sh script available
> Installing bird2 (2.15.1-r1) to root...
> Failed to connect to ubus
> Configuring bird2.
> Use package specific test.sh
> BIRD version 2.15.1
> Test failed
> ```

Need to add 2>&1 to redirect stderr to stdout

**Comment by bradfordzhang** [comment]
> CI fails:
> 
> ```
> Testing package bird2 in version  from bird2
> No pre-test.sh script available
> Installing bird2 (2.15.1-r1) to root...
> Failed to connect to ubus
> Configuring bird2.
> Use package specific test.sh
> BIRD version 2.15.1
> Test failed
> ```

It should be fixed now, thanks for your waiting~ :D

**Comment by tohojo** [comment]
What's the purpose of having this? Does is catch any actual errors?

**Comment by bradfordzhang** [comment]
> What's the purpose of having this? Does is catch any actual errors?

Just to test if bird is installed correctly.

**Comment by tohojo** [comment]
Bradford Zhang ***@***.***> writes:

>> What's the purpose of having this? Does is catch any actual errors?
>
> Just to test if bird is installed correctly.

But why is such a test useful? Did you run into any particular issue
where this test helps/would have helped? :)

**Comment by bradfordzhang** [comment]
> Bradford Zhang ***@***.***> writes:
> 
> >> What's the purpose of having this? Does is catch any actual errors?
> >
> > Just to test if bird is installed correctly.
> 
> But why is such a test useful? Did you run into any particular issue
> where this test helps/would have helped? :)
> 

In #1052 @BKPepe mentioned there is no test script for this package in CI, so this script just to make sure bird2 is installed correctly and can run without any error in dependency.

**Comment by tohojo** [comment]
Alright, makes sense. But please bump the package revision along with the change :)

**Comment by bradfordzhang** [comment]
> Alright, makes sense. But please bump the package revision along with the change :)

The version is bumped in previous commits

**Comment by tohojo** [comment]
Sure, but that's a week ago. PKG_RELEASE should be bumped along with this change or there will be two different packages with no indication of the change...

**Comment by bradfordzhang** [comment]
> Sure, but that's a week ago. PKG_RELEASE should be bumped along with this change or there will be two different packages with no indication of the change...

Got it, so i need to edit PKG_RELEASE to 2?

**Comment by BKPepe** [comment]
> Sure, but that's a week ago. PKG_RELEASE should be bumped along with this change or there will be two different packages with no indication of the change...

This file is not included in the package itself, it it just in this repository to be sure that bird does not segfault immediately or that it runs.

**Pull request merged**
