### PR TITLE
bird1: Add missing dependency on luci-compat

### PR DESCRIPTION
**Pull request by krzys-h**
Maintainer: @eloicaso

See https://forum.openwrt.org/t/luci-app-bird1-ipv4-errors/70288

### CODE REVIEW

**Comment by mwarning** [comment]
@eloicaso look good to me. yay or nay?

**Comment by rogerpueyo** [comment]
> @eloicaso look good to me. yay or nay?

Please proceed, @mwarning. I can confirm `luci-compat` needs to be installed every to make the `luci-app-bird1-ipv{4,6}` packages work.

**Review by rogerpueyo — APPROVED** [review]

**Comment by rogerpueyo** [comment]
@eloicaso, would you like me to become the package maintainer?

**Comment by rogerpueyo** [comment]
Maybe @aparcar would like to merge this? Ideally this should be backported to 22.03 and 21.02 (one line commit, no expected conflicts).

**Comment by mwarning** [comment]
OK, merged since the maintainer did not react.
@eloicaso is it OK if we make @rogerpueyo the maintainer for this package (if @rogerpueyo agrees, of course)?

**Comment by rogerpueyo** [comment]
Deal! I'll try to contact Eloi via an alternative e-mail, just in case he's not receiving these notifications.

**Pull request merged**
