### PR TITLE
oonf: fix compilation now that Ninja is in the tree.

### PR DESCRIPTION
**Pull request by neheb**
ping @mwarning

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@neheb Could you explain for me why it fixes the compilation?

**Comment by PolynomialDivision** [comment]
```
 Package HASH check failed
 ```

**Comment by neheb** [comment]
note that I haven't touched hashes.

It's needed because cmake.mk sets CMAKE_GENERATOR with a +. See https://github.com/openwrt/openwrt/commit/97258f53634d7237a2962aec3387f011047ce83b

Also see similar fixes: https://github.com/openwrt/openwrt/commit/09de28090cfb3fb605e6f4b452503a4ec2c6c43f

**Comment by PolynomialDivision** [comment]
There is no PKG_HASH at all. xD

**Pull request closed without merging**
