### PR TITLE
treewide: refactor to use PKG_BUILD_FLAGS

### PR DESCRIPTION
**Pull request by dhewg**
This refactors packages to use the new PKG_BUILD_FLAGS feature added to the main repo.

### CODE REVIEW

**Comment by dhewg** [comment]
Friendly ping.
The matching PRs on the packages, luci and telephony repos have been merged, it would be nice to get this is

**Comment by PolynomialDivision** [comment]
Looks fine for me.I'm waiting for @simonwunderlich ack since the changes are mostly affecting the packages of @simonwunderlich.

**Comment by dhewg** [comment]
Alright, thanks for that!

**Comment by dhewg** [comment]
Thanks!

**Pull request merged**
