### PR TITLE
ndppd: update to version 0.2.6

### PR DESCRIPTION
**Pull request by Red54**
Maintainer: @kerneis
Compile tested: x86-64, generic, snapshot
Run tested: x86-64, generic, snapshot

Description:
ndppd has tagged commit eb81b8f as 0.2.6.

https://github.com/openwrt/routing/pull/1082
https://github.com/DanielAdolfsson/ndppd/issues/90
https://github.com/DanielAdolfsson/ndppd/releases/tag/0.2.6

### CODE REVIEW

**Comment by mwarning** [comment]
I think the maintainer is @kerneis

**Comment by mwarning** [comment]
@Red54 please cahnge your commit message from "ndppd: bump to 0.2.6" to "ndppd: update to version 0.2.6"

**Comment by Red54** [comment]
@mwarning @kerneis done.

**Comment by kerneis** [comment]
I don't use openwrt anymore, feel free to transfer the maintainer role of my packages to whoever is relevant.

**Comment by mwarning** [comment]
ok, then lets merge. The MR looks OK to me but we do not have another maintainer anymore.

**Comment by mwarning** [comment]
@Red54 maybe you would like to maintain this package?

**Comment by Red54** [comment]
@mwarning okay, no problem.
https://github.com/openwrt/routing/pull/1087

**Pull request merged**
