### PR TITLE
oonf-olsrd2: add support to check if service is running

### PR DESCRIPTION
**Pull request by mkg20001**
Maintainer: @stargieg  / @XDjackieXD (find it by checking history of the package Makefile)
Compile tested: mips24k, master
Run tested: mips24k, ran service status / running commands

Description:
Adds the "running" and "status" commands.

Since olsr2 doesn't use procd, we need to add them by hand.

### CODE REVIEW

**Comment by XDjackieXD** [comment]
Looks good to me and is working on my ER-X-SFP

**Comment by mkg20001** [comment]
I've rebased so the tests are passing (there was some unrelated error about missing tarballs)

**Review by stargieg — APPROVED** [review]

**Review by stargieg — APPROVED** [review]
Looks fine for me.

**Comment by mkg20001** [comment]
Done

**Comment by blocktrron** [comment]
@PolynomialDivision is this ready now?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision is this ready now?

Looks good to me

**Pull request merged**
