### PR TITLE
[23.05] mesh11sd: update to version 3.1.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net

Compile tested: All

Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64
    On 23.5 and master/snapshot.

Description:
    mesh11sd (3.1.0)
    This release contains new functionality and numerous fixes.
    New functionality includes support of non-mesh segments of backhaul
    with blocking of bridge loops and spanning tree priority settable in the configuration

Details can be found here:
    https://github.com/openNDS/mesh11sd/releases/tag/v3.1.0

Signed-off-by: Rob White <rob@blue-wave.net>
(cherry picked from commit 4af9b69e1ba22a7406e20cdfb4982962e631fce4)

### CODE REVIEW

**Comment by bluewavenet** [comment]
@BKPepe 
Unfortunately we have the same CI issue here on 23.05....

**Comment by BKPepe** [comment]
That's bad, though. :) What are we going to do... 🤔 Let me do some cherry-picking magic, here.

**Comment by BKPepe** [comment]
I wanted rebase your PR, but unfortunately, it seems like you unchecked this option while creating PR:
image

Of course, it might be dangerous and we need to be carefull with that, I understand.

So, once you rebase your PR and force push it, CI/CD should work.

**Comment by BKPepe** [comment]
As always, glad to help. ;-)

**Pull request merged**
