### PR TITLE
mesh11sd: update to version 3.1.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net

Compile tested: All

Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64
    On 23.5 and master/snapshot.

Description:
    mesh11sd (3.1.0)
    This release contains new functionality and numerous fixes.
    New functionality includes support of non-mesh segments of backhaul
    with blocking of bridge loops and spanning tree priority settable in the configuration

Details can be found here:
    https://github.com/openNDS/mesh11sd/releases/tag/v3.1.0

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
Humph, "Hash of the downloaded file does not match".... Hold my beer.....

**Comment by bluewavenet** [comment]
@BKPepe  @mwarning 
The failures are all on "Build docker container" " no match for platform in manifest", so is this recent changes breaking CI for these architectures?

**Comment by BKPepe** [comment]
I'll look into it.

Dne pá 22. 3. 2024 9:14 uživatel Rob White ***@***.***>
napsal:

**Comment by bluewavenet** [comment]
@BKPepe 
Did you have time to take a look?

**Comment by BKPepe** [comment]
Yeah, I had, but unfortunately I had with me company notebook yesterday,
where almost everything is forbidden, thus I will backport the fix around
lunch time. Once, I do that, will let you know.

Dne pá 22. 3. 2024 22:36 uživatel Rob White ***@***.***>
napsal:

**Comment by BKPepe** [comment]
Please rebase your PR, it should be fixed.

**Comment by bluewavenet** [comment]
@BKPepe 
All passed!

**Comment by bluewavenet** [comment]
@BKPepe 
Thank you!

**Comment by BKPepe** [comment]
No problem. I'm glad I could help you

Dne po 25. 3. 2024 7:29 uživatel Rob White ***@***.***>
napsal:

**Pull request merged**
