### PR TITLE
mesh11sd: Release v2.0.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net
Compile tested: All
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02, 22.03 and snapshot.

Description:
mesh11sd (2.0.0)

This release contains new functionality.

Autonomous portal mode is introduced. This simplifies the rollout of meshnodes allowing a common configuration to be used on all nodes. Remote administration is introduced, allowing files to be copied and terminal sessions to be opened on established meshnodes, identifying remote nodes by mac address.

 * Add - Update config file [bluewavenet]
 * Add - implementation of remote copy [bluewavenet]
 * Add - implementation of remote connect [bluewavenet]
 * Add - Autonomous portal mode [bluewavenet]

-- Rob White dot@blue-wave.net Mon, 31 Jul 2023 16:59:52 +0000

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@BKPepe @PolynomialDivision @mwarning

**Comment by bluewavenet** [comment]
@mwarning @PolynomialDivision @BKPepe 

>  Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02, 22.03 and snapshot.

Note this has now also been tested on a stable release by a third party and shown to fix a critical bug.
openwrt/luci#6495

**Comment by mwarning** [comment]
@bluewavenet we should switch to a common commit title like e.g. "gnunet: update to version 0.19.4". That is what is used in the packages repo. :-)

**Comment by bluewavenet** [comment]
@mwarning 
You mean, instead of the format:
`mesh11sd: Release v2.0.0`

we should use:
`mesh11sd: Update to Version 2.0.0` ?

I don't have a strong opinion, other than I always try to be consistent from one release to another.

I am going to cherry-pick this to 23.05.
Is it still sensible to cherry-pick to 22.03? Presumably it is somewhere fairly close to EOL, but still currently "Stable Release" of course....

**Comment by mwarning** [comment]
> @mwarning You mean, instead of the format: `mesh11sd: Release v2.0.0`
> 
> we should use: `mesh11sd: Update to Version 2.0.0` ?
I meant `mesh11sd: update to version 2.0.0`

> 
> I don't have a strong opinion, other than I always try to be consistent from one release to another.
Me neither.

> 
> I am going to cherry-pick this to 23.05. Is it still sensible to cherry-pick to 22.03? Presumably it is somewhere fairly close to EOL, but still currently "Stable Release" of course....
Imho, cherry-picking this to 22.03 would still be sensible if it is not EOL. But I am not aware of any policies here.

**Comment by bluewavenet** [comment]
@mwarning 

> I meant mesh11sd: update to version 2.0.0

Did you intentionally use all lower case? ;-)
Which ever way you meant, I'll go with it - now I just need to remember.

I'll 2*cherry-pick early tomorrow morning - I'm too tired at the moment :-D

**Comment by mwarning** [comment]
Yes, the lower case is intentional :-)

**Pull request merged**
