### PR TITLE
quagga: reorder things in Makefile

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: unknown / not active
Compile tested: no, just reordering things
Run tested: no

Description:
- Fix SPDX License Identifier
- Use HTTPS in URL

cc: @neheb is this reordered correctly?

### CODE REVIEW

**Comment by neheb** [comment]
I'd put PKG_BUILD_PARALLEL below PKG_INSTALL. Looks better to have it in Christmas tree order.

**Comment by BKPepe** [comment]
Ok, thank you! 

I wanted to refresh patches, but I see many dead mirrors. :-(

```
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror.netcologne.de/savannah/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror.csclub.uwaterloo.ca/nongnu/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://ftp.acc.umu.se/mirror/gnu.org/savannah/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://nongnu.uib.no/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   232  100   232    0     0    401      0 --:--:-- --:--:-- --:--:--   400
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://ftp.igh.cnrs.fr/pub/nongnu/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20001 milliseconds
Warning: Problem : timeout. Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20001 milliseconds
Warning: Problem : timeout. Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20001 milliseconds
Warning: Problem : timeout. Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20001 milliseconds
Warning: Problem : timeout. Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Problem : timeout. Will retry in 16 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure ftp://cdimage.debian.org/mirror/gnu.org/savannah/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure ftp://ftp.acc.umu.se/mirror/gnu.org/savannah/quagga/quagga-1.2.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/quagga-1.2.4.tar.gz
```

I notified maintainers@quagga.net about it.

**Comment by BKPepe** [comment]
v1 - v2:

squashed fixups (Rosen's suggestion, refreshed patches)

**Comment by PolynomialDivision** [comment]
If you say the maintainer is not active/unknow, maybe remove it?

**Comment by BKPepe** [comment]
Isn't this issue with almost all packages in this repository?

**Comment by PolynomialDivision** [comment]
> Isn't this issue with almost all packages in this repository?

I maintain some packages in this repo, but a lot of others did not receive any updates for years. I also thought about pushing them to some archive or whatever.

**Comment by BKPepe** [comment]
That does not mean that packages are broken/not working.

**Comment by PolynomialDivision** [comment]
lgtm

**Pull request merged**
