### PR TITLE
oonf-olsrd2: a usable default configuration

### PR DESCRIPTION
**Pull request by stargieg**
Maintainer: @HRogge

Compile tested: mips_24kc, arm_cortex-a9_vfpv3-d16, i386_pentium4, x86_64, i386_pentium-mmx, mipsel_24kc

Description:
- OONF_OLSRV2_LAN_IMPORT for integration off other routing protocol (OLSR1, BGP, ...)
- OONF_OLSRV2_ROUTE_MODIFIER for overwriting the link quality of a neighbor, called LinkQuality Multiplicator in OLSR1
- OONF_GENERIC_REMOTECONTROL one of the goal of olsrv2
- OONF_OLSRV2_MPR reduce the routing graph when the network gets bigger

Signed-off-by: Patrick Grimm <patrick@lunatiki.de>

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Do you know why the CI fails?

**Comment by stargieg** [comment]
This Patch depends on https://github.com/openwrt/routing/pulls/stargieg

**Comment by PolynomialDivision** [comment]
Can you rebase on master?

**Comment by stargieg** [comment]
Done. But the queue is jammed.

**Comment by stargieg** [comment]
My Build Host
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
with
openwrt-sdk-ath79-generic_gcc-12.2.0_musl.Linux-x86_64

**Comment by stargieg** [comment]
I think #931 fix this.
But I cant' reproduce this because i don't have debian.
For me it compile with this #931

**Comment by mkg20001** [comment]
> Do you know why the CI fails?

It does look like the error #931 fixes

Since @stargieg reports that it builds with #931 aswell as without on his machine where the error didn't occur, I think the PR is good to merge. (it may be something about make being too old/new)

> But I can't reproduce this because i don't have debian.

You can try with docker (docker run -v $PWD:$PWD -it debian:stable)

**Comment by PolynomialDivision** [comment]
Thanks I merged it via https://github.com/openwrt/routing/pull/950

**Pull request closed without merging**
