### PR TITLE
bird2: bump to version 2.15.1

### PR DESCRIPTION
**Pull request by bradfordzhang**
Maintainer: @tohojo 
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by BKPepe** [comment]
Before I will approve it and merge, I do have question, though, because PR template was not filled. Was this compile and run tested on real device?

**Comment by bradfordzhang** [comment]
> Before I will approve it and merge, I do have question, though, because PR template was not filled. Was this compile and run tested on real device?

It hasn't been tested yet. Needs to be tested

**Comment by BKPepe** [comment]
Is it tested now?

**Comment by bradfordzhang** [comment]
> Is it tested now?

Tested

**Comment by tohojo** [comment]
Awesome, thanks!

**Pull request merged**
