### PR TITLE
[21.02] opennds: Release v9.1.1

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0-rc3, 19.07.7

Description:
This version fixes a compiler error, some compiler warnings and mutes a debug message
  * Fix - Compiler error, missing mode in call to open() [bluewave.net]
  * Fix - Compiler warning, ignored return value from call to lockf() [bluewave.net]
  * Fix - Compiler warning, ignored return value from call to system() [bluewave.net]
  * Fix - Compiler warning, ignored return value from call to fgets() [bluewave.net]
  * Fix - Remove debug message from call to get_client_interface library [bluewave.net]

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@mwarning 
Thankyou again!

**Comment by PolynomialDivision** [comment]
Next time maybe use `cherry-pick - x` to do the backport. ;) It is always good to have reference to trunk commit.

**Comment by mwarning** [comment]
Yeah, that would be the cherry-on-top :>

**Comment by bluewavenet** [comment]
Personally I prefer this:
https://zymurgorium.com/wp-content/uploads/cherry-on-top-bakewell-gin-liqueur.jpg

**Pull request merged**
