### PR TITLE
opennds: update to version 10.2.0

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Rob White rob@blue-wave.net

Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64

Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 23.05, 22.03

Description:
opennds (10.2.0) - This version is a minor upgrade that introduces some significant additional functionality.
In addition it includes numerous enhancements bug fixes and cosmetic fixes.

Additional functionality includes:

 * Pre-emptive Client Lists
 * Autonomous Block Lists
 * Internet hosted https FAS support for resource limited routers
 * Fair Usage Policy

Details can be found here:
https://github.com/openNDS/openNDS/releases/tag/v10.2.0

Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@mwarning @PolynomialDivision @BKPepe 
All tests passed. Good to go....

**Comment by BKPepe** [comment]
I do have one remark here. We don't need to copy&paste things from your tagged release in the commit description. Just point there your tag, where users which are interested in it can find it.

Overally, my idea is that in the commit description should be only relevant changes to package or files, which are here (init script, config file, etc.) and not describing all those changes which was done in the source code. It makes everything huge, which could lead to misunderstanding.

So...
commit description:

- Release notes:
https://github.com/openNDS/openNDS/releases/tag/v10.2.0

- Added one file, because smth...

**Comment by bluewavenet** [comment]
@BKPepe 
I have done it this way for some considerable time, born of frustration of finding commit/pr comments that convey almost zero information, making it very hard work to follow what is actually going on.

It is very refreshing to get feedback on this and yes I wholeheartedly agree with your idea as it will convey the same information as my method but in a much more condensed and readable form - for the same minimal effort that my verbose cut&paste involves.

I have edited accordingly. How does it look now?

**Comment by BKPepe** [comment]
Yeah, its better! You got the idea in the PR, which you edited. Good work. 

Next time, we can keep working on it to improve it even more. :)

Please do the same thing in your commit and force push it, then I will merge it.

**Comment by bluewavenet** [comment]
@BKPepe 

> Next time, we can keep working on it to improve it even more

Indeed.
A user guide or similar would be useful. Do you know if there is one? I can't find anything, particularly with regards to the many options for the makefile....

**Comment by bluewavenet** [comment]
@BKPepe 

> Please do the same thing in your commit and force push it, then I will merge it.

Done.

**Comment by bluewavenet** [comment]
@BKPepe 

Ready to go...

**Comment by BKPepe** [comment]
> A user guide or similar would be useful. Do you know if there is one? I can't find anything, particularly with regards to the many options for the makefile....

Hmm, I dont think so. :) Best practices applies here.

**Comment by bluewavenet** [comment]
@BKPepe 
Thank you!

> Best practices applies here.

Lol - So is there a list of best practices? ;-D

**Comment by BKPepe** [comment]
Haha, good joke. Nope. =D

**Pull request merged**
