### PR TITLE
cjdns: pass for dangling pointer warning

### PR DESCRIPTION
**Pull request by VenetiaFurtado**
Maintainer: @wfleurant 
Compile tested: builds for x86_64
Run tested: Build only testing

Description: same build error seen on my machine as seen in https://github.com/openwrt/routing/issues/958
Fix proposed is similar to https://github.com/openwrt/routing/issues/738

### CODE REVIEW

**Comment by BKPepe** [comment]
We can proceed further, but the formality check fails for you. Would you mind to fix it, please?

**Comment by wfleurant** [comment]
no objections

**Comment by wfleurant** [comment]
@cjdelisle please advise if you're not too busy

**Comment by cjdelisle** [comment]
Oh, that's a bug in cjdns. What version are you using? I can push a fix against that version.

**Comment by VenetiaFurtado** [comment]
It looks like version `v21.1` is being used.
 https://github.com/VenetiaFurtado/openwrt-routing/blob/master/cjdns/Makefile#L20

**Comment by cjdelisle** [comment]
I fixed the cause of the issue here: https://github.com/openwrt/routing/pull/964
Thanks for bringing this to my attention.

**Pull request closed without merging**
